### ISSUE TITLE
info TODO

### ISSUE THREAD

**Issue by suhyeon-0211** [suhyeon-0211/theman#2]
# TODO

- [x] 화면 마크업
- [ ] 모바일에서 지도 왜 안나오는지 체크
- [x] 메뉴 화면이랑 연동해서 값이 올바르게 나오는지 확인
- [x] 예약 화면이랑 연동해서 예약현황이 변경 여부 확인
- [x] 길찾기 코드 작성
- [x] 지도보기 코드 작성

**Comment by suhyeon-0211** [comment]
21-10-16~17 info 화면 마크업 및 길찾기, 지도보기 구현 완료
